### PR TITLE
Converter GUI and adding parameters.

### PR DESCRIPTION
**Pull request by SebastianDirks**
Added a small windows GUI tool to call the file converter using file dialogs.
 Added new function to the file converter: adding parameters to a parameterless file (tested with CLI files) by code.

### CODE REVIEW

**Comment by ax-meyer** [comment]
Hey Sebastian,

do you have dependencies that require WinForms? If not, I would suggest to switch over to WPF to support some more modern patterns (MVVM with bindings).

**Comment by SebastianDirks** [comment]
hm Ubuntu test pipeline is failing. All tests run fine now on my machine, Windows Net4.6 and .Net core. Unsure what the problem is, log only says 
2021-09-13T16:41:48.6330062Z Test Run Successful.
2021-09-13T16:41:48.6330845Z Total tests: 27
2021-09-13T16:41:48.6331499Z      Passed: 27
2021-09-13T16:41:48.6338519Z  Total time: 12.2752 Seconds
2021-09-13T16:41:53.6924083Z ##[error]Process completed with exit code 1.

**Comment by ax-meyer** [comment]
I can take a look at it tomorrow.

**Comment by SebastianDirks** [comment]
"SimpleJobWrite" called for /tmp/tmpqC7uqx.tmp.ovf
workPlane 0added!  progress [%]: 0
"SimpleJobWrite" called for /tmp/tmpb7lVBy.tmp.asp

Test Run Successful.
Total tests: 27
     Passed: 27
 Total time: 11.7645 Seconds
Error: Process completed with exit code 1.

Now I read in the log that the simple job write is called 3 times, but some of the calls seem to not complete because there is a progress % of 0 last. This looks like a problem with the async, that some code is not waiting for completion. Is it maybe that the GRPC wrapper is still writing async when the test already finishes? I'm just confused why this did not show up before, I have not changed any code that gets called there.

**Comment by ax-meyer** [comment]
I can check it, but it seems that all the tests pass. With the increased verbosity, the log shows some failed build. Although I don't really understand yet what build failed.

**Comment by SebastianDirks** [comment]
ah now I got it:
10:18:10.272    15>Done Building Project "/home/runner/work/OpenVectorFormatTools/OpenVectorFormatTools/OVFFileConverterGUI/OVFFileConverterGUI.csproj" (VSTest target(s)) -- FAILED.

the GUI is not building, guess because WinForms is only available on Windows? Can we simply exclude it from Linux build?

**Comment by ax-meyer** [comment]
The GUI is not being build anyhow... for Linux, I already specify which projects should be build, and the tests get started with the `--no-build` flag.

```
dotnet build --configuration Release --framework netcoreapp2.1 ReaderWriter/FileReaderWriterFactoryGRPCWrapper/FileReaderWriterFactoryGRPCWrapper.csproj
dotnet build --configuration Release --framework netcoreapp2.1 ReaderWriter/UnitTests/UnitTests.csproj
dotnet build --configuration Release --framework netcoreapp2.1 PlausibilityChecker/PlausibilityCheckerUnitTests/PlausibilityCheckerUnitTests.csproj

dotnet run --configuration Release --framework netcoreapp2.1 --project ReaderWriter/FileReaderWriterFactoryGRPCWrapper/FileReaderWriterFactoryGRPCWrapper.csproj background &

dotnet test --no-build --configuration Release --framework netcoreapp2.1
```

It seems like the test framework wants to test something that wasnt' build?

**Comment by ax-meyer** [comment]
I specified the exact projectes to run tets on - not the best solution since new projects with tests won't be auto-discovered.

But the Linux pipeline now passes, however, the Windows one seems to fail with the same problem - maybe the GUI components are somehow missing on headless windows instance in the runner?

**Comment by ax-meyer** [comment]
Found an error directly at the start of the build command:

`D:\a\OpenVectorFormatTools\OpenVectorFormatTools\OVFFileConverterGUI\OVFFileConverterGUI.csproj : warning NU1503: Skipping restore for project 'D:\a\OpenVectorFormatTools\OpenVectorFormatTools\OVFFileConverterGUI\OVFFileConverterGUI.csproj'. The project file may be invalid or missing targets required for restore. [D:\a\OpenVectorFormatTools\OpenVectorFormatTools\OpenVectorFormatTools.sln]`

Can you check your project file?

**Comment by ax-meyer** [comment]
It seems this was also the underlying issue for the linux tests, at least on my local machine. I restored the CI-tests for Linux to the previous state.

If all tests pass now, we can merge, fine for me.

**Pull request merged**
