### PR TITLE
Ovf file structure description

### PR DESCRIPTION
**Pull request by ax-meyer**
I added an description for the OVF File structure so that someone else could implement a compatible reader / writer in another language.

Furthermore, added checks & conversion in the C# code to make sure that the LUT indices are always written as LittleEndian.

@SebastianDirks Can you (or the Hiwi who implemented the simultaneous reading / writing of WorkPlanes for the file structure) sanity check my description? Since I didn't implement it, I reconstructed it from the code, I may still have gotten something wrong in the logic there.

### CODE REVIEW

**Comment by SebastianDirks** [comment]
The Hiwi is MStorm90. I added him for short review.

**Comment by SebastianDirks** [comment]
There was a suggestion brought to me to move the ovf_lut.proto and this definitions to the definition repo because of licensing issues when parsing OVF files using the LUT which here has a GPL. Should we maybe tackle that in one step?

**Comment by ax-meyer** [comment]
Oh, I hadn't thought of this yet, yes, sounds good.

Will you do the move or should I?

**Comment by SebastianDirks** [comment]
I added an explanation of delimited methods and pitfalls in e.g. C++. Can you do the move @ax-meyer?

**Comment by ax-meyer** [comment]
I moved the ovf_lut.proto file to the OpenVectorFormat repository, including the documentation. As soon as the pr is merged there, I will push the updated Tools projects with the reference for the correct commit in the submodule.

**Review by MStorm90 — APPROVED** [review]

**Pull request merged**
